# Generated by Django 4.2.7 on 2023-11-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='user',
        ),
    ]
